"""
HypothesisCMOM.py
=================
cMOM — Constant Volatility-Scaled Momentum

Time-series momentum strategy adapted for single-asset pipeline execution.

Signal: +1 when 12-month momentum (skipping last month) is positive and
volatility-adjusted position size exceeds threshold; -1 when momentum is
strongly negative and vol-adjusted sizing flips the signal; 0 otherwise.

Scaling: Realized volatility of daily momentum returns is computed each day
using a 126-day window. The target volatility σ_target is set to the full-sample
volatility of the momentum series. The scaling weight w_t = σ_target / σ_realized,t
is applied, with a hard cap of 5.0 per Barroso & Santa-Clara (2015).

Paper: Hanauer & Windmuller (2022), "Enhanced Momentum Strategies", SSRN 3437919
Based on: Barroso & Santa-Clara (2015)
"""
import SopaDeOtoe._path_setup  # noqa: F401

import numpy as np
import pandas as pd
from src.strategy import BaseStrategy


class HypothesisCMOM(BaseStrategy):
    """
    Constant Volatility-Scaled Time-Series Momentum.

    Uses 12-2 month formation period (skipping last month to avoid reversal).
    Signals are generated by comparing vol-scaled momentum to a rolling threshold.
    When realized vol is high, position size is reduced; when low, increased.
    """

    def __init__(
        self,
        mom_formation: int = 252,
        mom_skip: int = 21,
        vol_lookback: int = 126,
        weight_cap: float = 5.0,
        signal_thresh: float = 0.0,
        close_col: str = "Close",
        **kwargs,
    ):
        """
        Parameters
        ----------
        mom_formation : int
            Number of trading days for momentum formation (default 252 = ~12 months).
        mom_skip : int
            Number of days to skip at end of formation window (default 21 = ~1 month
            to avoid short-term reversal, per Jegadeesh & Titman).
        vol_lookback : int
            Number of days for realized volatility estimation (default 126 = ~6 months).
        weight_cap : float
            Maximum scaling weight (default 5.0, per Barroso & Santa-Clara).
        signal_thresh : float
            Threshold for signal generation in vol-adjusted space (default 0.0).
        close_col : str
            Price column name in features DataFrame.
        """
        self.mom_formation = int(mom_formation)
        self.mom_skip = int(mom_skip)
        self.vol_lookback = int(vol_lookback)
        self.weight_cap = float(weight_cap)
        self.signal_thresh = float(signal_thresh)
        self.close_col = close_col

        # Cached state
        self._target_vol: float = None

    def generate_signals(self, features: pd.DataFrame) -> pd.Series:
        close = features[self.close_col]

        # Daily log returns
        log_ret = np.log(close / close.shift(1)).fillna(0)

        # Rolling cumulative momentum: sum of log returns over formation period
        # shift(mom_skip) skips the most recent month to avoid reversal
        mom = log_ret.shift(self.mom_skip).rolling(
            window=self.mom_formation, min_periods=self.mom_formation
        ).sum()
        mom = mom.shift(1)  # avoid look-ahead bias

        # Realized volatility of momentum series (rolling)
        realized_vol = log_ret.rolling(
            window=self.vol_lookback, min_periods=self.vol_lookback
        ).std(ddof=0) * np.sqrt(21)  # annualized

        # Volatility scaling weight: w_t = σ_target / σ_realized,t
        if self._target_vol is None:
            warmup = self.mom_formation + self.mom_skip + self.vol_lookback
            if len(log_ret) > warmup:
                self._target_vol = realized_vol.iloc[warmup:].mean()
            else:
                self._target_vol = 0.05  # fallback

        vol_adj = (self._target_vol / realized_vol.clip(lower=1e-8)).fillna(1.0)
        vol_adj = vol_adj.clip(upper=self.weight_cap)

        # Vol-adjusted momentum signal
        mom_scaled = mom * vol_adj

        # Generate signals: +1 long when scaled momentum above threshold,
        # -1 short when scaled momentum below negative threshold
        sig = pd.Series(0, index=features.index, dtype=int)
        sig[mom_scaled > self.signal_thresh] = 1
        sig[mom_scaled < -self.signal_thresh] = -1

        # Warmup
        warmup = self.mom_formation + self.mom_skip + self.vol_lookback
        sig.iloc[:warmup] = 0

        return sig
