/**
 * Real data loader for SopaDeOto dashboard.
 * Reads from JSON results generated by the SopaDeOto pipeline.
 */

import * as fs from "fs";
import * as path from "path";

import type {
  PortfolioResult,
} from "./types";

// ─── Paths ──────────────────────────────────────────────────────────────────

const PORTFOLIO_DIR = "/Users/nongo/Documents/Patacon/SopaDeOtoe/results/portfolio";
const EXPLORATION_DIR = "/Users/nongo/Documents/Patacon/SopaDeOtoe/results/exploration";

// ─── Portfolio ───────────────────────────────────────────────────────────────

export function loadPortfolioResult(): PortfolioResult | null {
  try {
    const files = fs.readdirSync(PORTFOLIO_DIR)
      .filter((f: string) => f.startsWith("first_cohort_") && f.endsWith(".json"))
      .sort()
      .reverse();

    if (files.length === 0) return null;
    const raw = fs.readFileSync(path.join(PORTFOLIO_DIR, files[0]), "utf-8");
    return JSON.parse(raw) as PortfolioResult;
  } catch {
    return null;
  }
}

// ─── Equity Curve ────────────────────────────────────────────────────────────

const STRATEGY_MAP: Record<string, string> = {
  HypothesisH236MomentumReversalAsym_f7c925d4: "HypothesisH236MomentumReversalAsym_021821",
  TSIMeanReversion_11c86993: "TSIMeanReversion_095404",
  HypothesisH110BollingerKyleGate_bc9371eb: "HypothesisH110BollingerKyleGate_160334",
  HypothesisH203VolExpansionEntry_6edcbb5c: "HypothesisH203VolExpansionEntry_012006",
  HypothesisH167BollingerRangingOFIGate_a40f8e2c: "HypothesisH167BollingerRangingOFIGate_162324",
  HypothesisH318TrendlineChannelSqueeze_19e38d5f: "HypothesisH318TrendlineChannelSqueeze_051527",
  HypothesisH37DynamicGridInformedGate_4b2e513b: "HypothesisH37DynamicGridInformedGate_051820",
  DualMovingAverageCrossover_767ba598: "DualMovingAverageCrossover_162631",
  MultiTimeframeTrendSignal_e5ce17eb: "MultiTimeframeTrendSignal_134237",
};

export async function buildEquityCurve(
  weights: Record<string, number>,
  startDate = "2023-01-01"
): Promise<any[]> {
  const files = fs.readdirSync(EXPLORATION_DIR).filter((f: string) => f.endsWith("_REPRO.json"));

  const series: Record<string, number[]> = {};

  for (const [hashId, filePrefix] of Object.entries(STRATEGY_MAP)) {
    if (!(hashId in weights)) continue;
    const match = files.find((f: string) => f.startsWith(filePrefix));
    if (!match) continue;
    try {
      const raw = fs.readFileSync(path.join(EXPLORATION_DIR, match), "utf-8");
      const d = JSON.parse(raw) as { daily_returns?: number[] };
      if (d.daily_returns) series[hashId] = d.daily_returns;
    } catch { /* skip */ }
  }

  const allLens = Object.values(series).map((s) => s.length);
  const minLen = Math.min(...allLens);
  if (minLen === 0 || !isFinite(minLen)) return [];

  // Align and compute weighted portfolio returns
  const aligned: Record<string, number[]> = {};
  for (const [k, v] of Object.entries(series)) {
    aligned[k] = v.slice(v.length - minLen);
  }

  const portfolioReturns: number[] = [];
  for (let i = 0; i < minLen; i++) {
    let r = 0;
    for (const [hashId, rets] of Object.entries(aligned)) {
      r += (weights[hashId] ?? 0) * rets[i];
    }
    portfolioReturns.push(r);
  }

  // Build equity curve from 1
  let equity = 1;
  const start = new Date(startDate);
  const points: any[] = [{ date: startDate, value: equity }];

  for (let i = 0; i < portfolioReturns.length; i++) {
    equity *= 1 + portfolioReturns[i];
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    const dateStr = d.toISOString().split("T")[0];
    points.push({ date: dateStr, value: equity });
  }

  return points;
}

export function buildDrawdownBands(equityCurve: any[]): any[] {
  let peak = equityCurve[0]?.value ?? 1;
  return equityCurve.map((pt) => {
    if (pt.value > peak) peak = pt.value;
    const dd = (pt.value - peak) / peak;
    return { date: pt.date, drawdown: dd, equity: pt.value };
  });
}

// ─── Strategy Metrics ────────────────────────────────────────────────────────

export interface StrategyMetricRow {
  name: string;
  sharpe: number;
  total_return: number;
  max_drawdown: number;
  calmar: number;
  sortino: number;
  grade: string;
}

export async function loadStrategyMetrics(
  _weights: Record<string, number>
): Promise<StrategyMetricRow[]> {
  const files = fs.readdirSync(EXPLORATION_DIR).filter((f: string) => f.endsWith("_REPRO.json"));
  const rows: StrategyMetricRow[] = [];

  for (const [hashId, filePrefix] of Object.entries(STRATEGY_MAP)) {
    const match = files.find((f: string) => f.startsWith(filePrefix));
    if (!match) continue;
    try {
      const raw = fs.readFileSync(path.join(EXPLORATION_DIR, match), "utf-8");
      const d = JSON.parse(raw) as { metrics?: Record<string, number> };
      const m = d.metrics ?? {};
      const shortName = hashId.replace(/_[a-f0-9]{8}$/, "");
      rows.push({
        name: shortName,
        sharpe: m.sharpe ?? 0,
        total_return: m.cum_return ?? 0,
        max_drawdown: m.max_drawdown ?? 0,
        calmar: m.calmar ?? 0,
        sortino: 0,
        grade: gradeFromSharpe(m.sharpe ?? 0),
      });
    } catch { /* skip */ }
  }
  return rows;
}

function gradeFromSharpe(s: number): string {
  if (s >= 1.5) return "Excellent";
  if (s >= 1.0) return "Good";
  if (s >= 0.5) return "Fair";
  return "Poor";
}

// ─── Method Comparison (for Rebalance page) ────────────────────────────────

export interface MethodComparisonResult {
  method: string;
  fdm: number;
  weights: Record<string, number>;
  sharpe?: number;
  sortino?: number;
  max_dd?: number;
}

export function loadMethodComparison(): MethodComparisonResult[] {
  try {
    const files = fs.readdirSync(PORTFOLIO_DIR)
      .filter((f: string) => f.startsWith("method_comparison_") && f.endsWith(".json"))
      .sort()
      .reverse();

    if (files.length === 0) return [];
    const raw = fs.readFileSync(path.join(PORTFOLIO_DIR, files[0]), "utf-8");
    const data = JSON.parse(raw) as { methods: MethodComparisonResult[] };
    return data.methods ?? [];
  } catch {
    return [];
  }
}
